# Étape 1 : Construction (builder)
FROM node:16-bullseye-slim AS builder

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer toutes les dépendances (y compris les devDependencies)
RUN npm install

# Copier l'ensemble du projet
COPY . .

# Compiler l'application avec SWC (les devDependencies sont présentes)
RUN npm run build

# Étape 2 : Exécution (runner)
FROM node:16-bullseye-slim AS runner

WORKDIR /app

# Copier uniquement les fichiers de dépendances
COPY package*.json ./

# Installer uniquement les dépendances de production
RUN npm install --production

# Copier les fichiers compilés depuis l'étape builder
COPY --from=builder /app/dist ./dist

# Exposer le port sur lequel l'application tourne
EXPOSE 3000

# Démarrer l'application
CMD ["node", "dist/main.js"]
